#include <iostream>
using namespace std;
int main() {
    string y_or_n;
    string Yes_Or_No;
    string yes_or_no;
	int result;
	int y;
	int num = 20;
	int num2 = 5;
	int answer;
	int x;
	int first= 4;
	int second= 5;
	int perform;
	int a;
	int Number1 = 6;
	int Number2 = 2;
	string ys_o_no;
	cout << "Welcome To Number Guesser.\n";
	cout << "Think a Number, Multiply It By 4 And Add 5 To It.\n";
	cout << "Tell Your Result: ";
	cin >> x;
	answer = x;
	int first_step = answer - second;
	int solution = first_step/first;
	cout << "The Number In Your Mind Is: ";
	cout << solution << "\n";
	cout << "Next One: \n";
	cout << "Think A Number, Add 20 To It And Subtract 5 From It.\n";
	cout << "Tell Your Result: ";
	cin >> result;
	int first_step2 = result + num2;
	int second_step = first_step2 - num;
	cout << "The Number In Your Mind Is: ";
	cout << second_step << "\n";
	cout << "Think a Number, Divide it by 6 and Subtract 2 from it.\n";
	cout << "Tell Your Result: ";
	cin >> perform;
	int first_step3 = perform + Number2;
	int Answer= first_step3 * Number1;
	cout << "The Number In Your Mind Is: ";
	cout << Answer << "\n";
	cout << "Thanks. Visit Again Next Time.\n";
	cout << "\n";
	cout << "Press Enter To Exit: ";
	cin.get();
	cin.get();
	return 0;
}
